### ISSUE TITLE
panel_save_workflow cannot save ANY never-persisted workflow on frontend 1.47.10 — "save-as (copy) is unavailable on this frontend"

### ISSUE THREAD

**Issue by artokun** [artokun/comfyui-mcp-panel#268]
### What happened / root cause

`panel_save_workflow` fails for **every brand-new workflow** created with `panel_new_workflow` — with a name, and also with no args at all (the documented "auto-name and persist" path). The tool description promises: *"A never-saved workflow is auto-named and persisted; pass `name` to give it (or rename it to) a specific name."* None of that works on ComfyUI frontend **1.47.10**.

Traced to `web/js/lib/workflow-save.js` → `saveActiveWorkflow()`. Two independent causes stack up:

**(1) `svc.saveWorkflowAs` is not a function on frontend 1.47.10.**
`svc` is `app.extensionManager.workflow` (`comfyui-mcp-panel.js:2358`). The guard at `workflow-save.js:140` (`if (typeof svc.saveWorkflowAs === "function")`) is false, so control falls through to the legacy fallback at :177–185. The copy API the whole safe path depends on is either renamed or no longer surfaced on `extensionManager.workflow` in 1.47.x.

**(2) `classifySource()` returns `"unknown"` for a genuinely never-persisted tab, so the fallback refuses.**
For a fresh tab, `wf.path` is `"workflows/Unsaved Workflow (2).json"` — non-empty — so the `!norm → "never-persisted"` shortcut at :235 is skipped. The oracle `svc.getWorkflowByPath(rawPath)` then returns **the temporary workflow object itself** (`isPersisted === false`), which is neither `found.isPersisted === true` (→ not `persisted`) nor `found == null` (→ not `confirmedAbsent`). Both flags stay unset → `"unknown"` → the fallback at :177 requires `"never-persisted"` → throws at :183.

Net effect: on 1.47.10 the *only* reachable outcome for a new workflow is the refusal. The `#226` data-loss guard is doing its job (fail-safe), but the safe path it's supposed to route to no longer exists, so "save my new workflow" is 100% broken.

Confirming the diagnosis: after `panel_rename_workflow("<name>")`, a subsequent bare `panel_save_workflow()` **succeeds** — because `currentName` is then a non-default name, `desired` is `""`, `effectiveName === currentName`, `finalTargetPath === currentPath`, so `relocates === false` and it takes the `saveInPlace()` branch (:190), never entering the relocation logic at all.

### Steps to reproduce

1. `panel_new_workflow` (tab is "Unsaved Workflow (2)", `isTemporary: true`, `isPersisted: false`).
2. Add any node.
3. `panel_save_workflow({ name: "My Workflow" })` → error.
4. `panel_save_workflow()` (no args) → **same** error.
5. Workaround: `panel_rename_workflow({ name: "My Workflow" })`, then `panel_save_workflow()` → succeeds.

### Exact error (scrubbed)

```
Error: save-as (copy) is unavailable on this frontend; refusing to rename and destroy the original workflow
```
(thrown at `web/js/lib/workflow-save.js:183-185`)

### Fix

**applied locally: no**  **upstream-only: yes**

Not patched deliberately. This is the `#226` data-loss-guarded module; the installed pack has no `.git` and no test suite, so the Step-4 safety gate (`npm test` over `workflow-save.js`'s unit tests) can't be run here. Patching a destructive-move guard without being able to prove the invariant still holds is exactly the case that should be escalated rather than hot-fixed. Precise changes needed:

**(a) Restore the copy API on 1.47.x.** Find where `saveWorkflowAs` now lives on the 1.47 frontend and probe it (likely `workflowStore.saveAs`, or a renamed method on `extensionManager.workflow`). Probing a list of candidates keeps back-compat:

```js
const saveAsFn =
  (typeof svc.saveWorkflowAs === "function" && svc.saveWorkflowAs.bind(svc)) ||
  (typeof svc.saveAs === "function" && svc.saveAs.bind(svc)) ||
  null;
if (saveAsFn) { /* existing copy path, using saveAsFn(wf, { filename: effectiveName }) */ }
```

**(b) Give `classifySource()` a real filesystem oracle instead of the in-memory store.** The in-memory `getWorkflowByPath` can never prove absence for an open tab — it returns the tab. An authoritative probe is ComfyUI's userdata API:

```js
// 404 ⇒ provably no file backs this path ⇒ "never-persisted"
const res = await fetch(`/api/userdata/${encodeURIComponent(rawPath)}`, { method: "HEAD" });
if (res.status === 404) return "never-persisted";
if (res.ok) return "persisted";
return "unknown"; // network/other error ⇒ fail safe, unchanged
```

This makes `classifySource` async (and `saveActiveWorkflow` already is), and it *strengthens* the `#226` invariant rather than weakening it — today's "unknown" is a guess from a store that can't see disk; a 404 from userdata is real proof. It also fixes the drifted-temporary case (#215) correctly: a tab wrongly flagged temporary whose file **does** exist returns `res.ok` → `"persisted"` → still refuses to move.

**(c) Cheap interim mitigation** (if a full fix isn't imminent): when `relocates && cls !== "never-persisted"` and no copy API exists, fall back to `svc.renameWorkflow(wf, finalTargetPath)` **only** when `wf.isTemporary === true && wf.isPersisted === false && isDefaultWorkflowName(currentName)` — i.e. reproduce exactly what `panel_rename_workflow` already does today, which is the workaround users are forced into manually anyway. Note the current asymmetry is itself a hole: `panel_rename_workflow` performs the very move that `panel_save_workflow` refuses, so the guard isn't actually closing the path it's protecting.

**(d) Also worth a look:** `groundUnsavedWorkflow()` (`comfyui-mcp-panel.js:2365`) swallows this error silently (`catch { return null }`), so every new workflow is silently left ungrounded for the agent with no signal that grounding failed.

### Environment

- OS: Windows 11 Pro 10.0.26200
- ComfyUI: 0.29.0 (local, Comfy-Desktop install)
- **comfyui_frontend_package: 1.47.10** ← the relevant version
- **comfyui-mcp: 0.48.11**
- **comfyui-mcp-panel: 0.11.8**
- GPU: NVIDIA RTX 3080 (10 GB VRAM), CUDA 13.0, torch 2.10.0+cu130, Python 3.13.12

**Comment by artokun** [comment]
Fixed in **panel 0.11.11** (#273): panel_save_workflow now saves new/never-persisted workflows on ComfyUI frontend 1.47.x again. Root cause was the 1.47 frontend removing `saveWorkflowAs` from the store, so the #226 data-loss guard's safe path was gone and it fail-safe-refused. Fix probes the copy API across frontends (saveWorkflowAs on 1.45.x, or saveAs+openWorkflow+saveWorkflow on 1.47.x — mirroring upstream so the real graph is persisted, never null) and uses a /userdata filesystem oracle to tell a genuinely-new tab from a drifted real file. The #226 no-data-loss invariant is preserved. Update to 0.11.11; reopen if it persists.
