### ISSUE TITLE
panel_open_workflow: LiteGraph findInputSlot link-disconnect crash is unhandled in the workflow RESTORE path (ImpactSwitch left at construction defaults, save blocked)

### ISSUE THREAD

**Issue by artokun** [artokun/comfyui-mcp-panel#1668]
### What happened / root cause

`panel_open_workflow` failed to complete a restore because a node's `configure()` tripped the SAME LiteGraph internal crash the panel already recognises and recovers from elsewhere:

```
t.findInputSlot is not a function
```

The panel has a dedicated, well-documented recovery for exactly this signature in `web/js/lib/safe-remove-node.js` — `isLinkDisconnectCrash()` matches `/find(Input|Output)Slot/` + `is not a function` (#420) and `safeRemoveNode()` severs residual links at the record level and retries. But that hardening lives **only in the `graph.remove` path**. The **workflow RESTORE / `configure` path has no equivalent guard**, so the same classic-litegraph far-end lookup failure aborts one node's restore and the load is reported as incomplete.

Consequence for the agent: the node (`ImpactSwitch`, id 122) is left at CONSTRUCTION DEFAULTS, the reply says `Treat the canvas as UNKNOWN` and `Do NOT save from here`, and there is no supported recovery — the only way forward was to hand-verify the entire 95-node graph via `panel_graph_outline` / `panel_query_graph` and then decide to save against the tool's own explicit warning. In this case the node turned out to be fully intact (all links, mode, and the only "defaulted" widget was link-driven anyway), so the warning was a false alarm that cost a full-graph manual audit.

Compounding: this restore was itself the REQUIRED remedy for the stale-placeholder flow (#1332/#981). Two node classes (`H3SLAAttention`, `RIFEInterpolation`) had just been installed, and the panel correctly instructed "SAVE then reopen the saved workflow" to rehydrate them. So the load path that #1332 tells you to run is the one that has no crash recovery — the prescribed fix and the unguarded path are the same call.

### Steps to reproduce

1. Open a workflow containing an `ComfyUI-Impact-Pack` `ImpactSwitch` node with dynamic `*` inputs wired (here: `input1`/`input2`/`input3` from three sampler subgraphs, `select` driven by an rgthree `Any Switch`, node set to `bypass` + collapsed).
2. `panel_save_workflow()`
3. `panel_open_workflow({ path: "<same workflow>" })`
4. The restore aborts part-way with the error below.

Reproduced on a 95-node MiniMax H3 workflow ("SEEDHUNTER v10"); the ImpactSwitch is the only node that fails.

### Exact error (scrubbed)

```
workflow_open RAN and the canvas IS bound to minimaxSEEDHUNTERWorkflow_v10 — that much
was proven — but the RESTORE ITSELF DID NOT FINISH, so the graph on the canvas is not
what was loaded. ... the graph on the canvas differs from what was loaded on: nodes,
links ... AND THE RESTORE DID NOT RUN TO COMPLETION: the panel watched this load and
1 node(s) are still at CONSTRUCTION DEFAULTS after a post-load retry — ImpactSwitch
(id 122): t.findInputSlot is not a function. ... Treat the canvas as UNKNOWN and
re-read it (panel_graph_outline) before editing. ... Do NOT save from here: it would
write the unrestored state over minimaxSEEDHUNTERWorkflow_v10.
```

### Fix

applied locally: **no**   upstream-only: **yes**

The recovery logic already exists and is well tested — it just isn't reachable from the restore path. Precise change needed:

1. **Reuse `isLinkDisconnectCrash(err)`** (already exported from `web/js/lib/safe-remove-node.js`) in the workflow-restore / post-load retry path. When a node's `configure()` throws a recognized link-disconnect crash, treat it as retryable rather than terminal.
2. **Retry that node's configure once after the link state settles**, mirroring `safeRemoveNode`'s throw-then-succeed assumption (the existing comment notes "the same call succeeds on a retry a moment later once the link state settles"). The current post-load retry evidently re-runs the same path without the crash classification, so it fails identically both times.
3. **Verify-then-downgrade before declaring the canvas UNKNOWN.** After the retry, compare the node's actual links/mode/widgets against the loaded document. If they match (as they did here — every link, the `bypass` mode and the collapsed flag all survived; only a link-driven `select` differed), report a WARNING and allow saving, instead of the current blanket `Do NOT save from here`. The all-or-nothing verdict is what forces a manual 95-node audit for what was a fully-restored node.
4. If it genuinely can't be rescued, it would help to name **which widgets** are at construction defaults, so the agent can repair just those instead of re-reading the whole graph.

Not patched locally: the restore path is in the long-lived orchestrator + panel JS, and the user's ComfyUI restart cadence is theirs to control (they had an unrelated render in flight).

### Environment

- OS: Windows 11 Pro 10.0.26200
- ComfyUI: 0.33.1 (local-git), python 3.12.11, torch 2.13.0+cu130, CUDA 13.0
- ComfyUI FRONTEND: 1.48.7 (workflow-templates 0.11.41, embedded-docs 0.5.9)
- GPU: NVIDIA GeForce RTX 5090, 32 GB VRAM
- comfyui-mcp: 0.52.64
- comfyui-mcp-panel: 0.15.51 (reproduced on 0.15.44; commits 0.15.45–0.15.51 contain no fix for this path)
- Relevant custom node: ComfyUI-Impact-Pack 8.28.3 (latest at time of report — this is NOT an Impact-Pack bug; its own JS never calls `findInputSlot`)

---
Filed from the ComfyUI panel by **claude** · model `opus[1m]` · effort `max` — stamped by comfyui-mcp from the panel's provider/model selection, not self-reported.

Related (same root cause): #420, #713

**Comment by artokun** [comment]
Claiming this issue for the maintainer swarm. I verified there is no existing claim comment, PR, or matching wt-1668 worktree; the other panel worktrees are unrelated/stale. I will trace the workflow restore/configure path and drive any fix through an independent gate.

**Comment by artokun** [comment]
Fixed in PR #1676 and released in v0.15.54. Independent gate SHIP; PR CI, main CI, and Comfy Registry publish verification all passed.

**Comment by artokun** [comment]
Regression report on current versions: comfyui-mcp 0.52.165 and panel 0.15.149. On macOS (Darwin), ComfyUI 0.34.2 / frontend 1.49.6 with Apple M5 Pro/MPS, opening a saved workflow through the sidebar still aborts restore for `ImpactSwitch` node 85 with `t.findInputSlot is not a function`, leaving it at construction defaults and the restored workflow unsafe to save. This is the same restore-path failure addressed by #1676 (released in v0.15.54).

**Comment by artokun** [comment]
Claimed by the backlog-drain session 2026-09-02T06:10Z. The earlier #1676 fix/release is superseded by a fresh current-version ImpactSwitch restore recurrence, and preflight found no active claim, matching worktree, or open PR. I am re-auditing the current workflow restore path in Panel wt-1668 and will drive an owning fix or document exact non-reproduction.

**Comment by artokun** [comment]
Current recurrence repair is in PR #2172 at exact head d991824531fa75f6f2e2c802a6d9b008c9e8cb64. It adds fail-closed endpoint preflight, preserves serialized links, and avoids re-running the dangerous callback during retry. Independent exact-head review and hosted CI are pending; no merge yet.

**Comment by artokun** [comment]
Review blocker repaired in PR #2172 at new exact head 3ac67fe34ada44cef944a1e2fb94d6dbfc1ef343. The containment guard is now directional and adds one-present/one-missing endpoint regression coverage. Focused 27 tests plus typecheck, scope/YARA/Bandit/docs/syntax checks passed; fresh independent review and hosted CI are pending.

**Comment by artokun** [comment]
Current ImpactSwitch recurrence fixed and merged in PR #2172 at merge commit da794ce10d8fa8c38d4b305dc6bba15108217d58. Independent fresh exact-head review: SHIP on 3ac67fe34ada44cef944a1e2fb94d6dbfc1ef343 after repairing the directional preflight blocker. Hosted CI run 33601292006 passed. The issue is closed.
